const std = @import("std");
const zag = @import("zag");

// The fixtures module is generated by tests/fixtures/gen.sh, which
// build.zig runs before this module compiles. Adding a new fixture
// means dropping an NN_foo.py into tests/fixtures/ and re-running the
// test -- no change here.
const fixtures = @import("fixtures");

test "fixtures match CPython output" {
    inline for (fixtures.names) |name| {
        runFixture(
            name,
            @embedFile("fixtures/" ++ name ++ ".cpython-314.pyc"),
            @embedFile("fixtures/" ++ name ++ ".expected.txt"),
        ) catch |err| {
            std.debug.print("fixture {s} failed: {s}\n", .{ name, @errorName(err) });
            return err;
        };
    }
}

fn runFixture(name: []const u8, pyc: []const u8, expected: []const u8) !void {
    _ = name;
    var dbg: std.heap.DebugAllocator(.{}) = .init;
    defer _ = dbg.deinit();
    const gpa = dbg.allocator();

    var run_arena: std.heap.ArenaAllocator = .init(gpa);
    defer run_arena.deinit();
    const run_alloc = run_arena.allocator();

    const code = try zag.marshal.pyc.loadBytes(run_alloc, pyc);

    var out_buf: [64 * 1024]u8 = undefined;
    var writer = std.Io.Writer.fixed(&out_buf);
    var stderr_buf: [4 * 1024]u8 = undefined;
    var stderr_writer = std.Io.Writer.fixed(&stderr_buf);

    var interp = try zag.vm.interp.Interp.init(run_alloc, &writer, &stderr_writer);
    try interp.installBuiltins();
    _ = try interp.run(code);
    try writer.flush();

    try std.testing.expectEqualStrings(expected, writer.buffered());
}
