const std = @import("std");
const zag = @import("zag");

// Embedded so the test doesn't need a std.Io: tests don't get a
// std.process.Init, and Zig 0.16 routes file reads through std.Io.Dir.
// The .pyc is generated by tests/fixtures/gen.sh, which build.zig runs
// before this module compiles.
const hello_pyc = @embedFile("fixtures/00_hello.cpython-314.pyc");
const hello_stdout = @embedFile("fixtures/00_hello.expected.txt");

test "00_hello: print builtin matches CPython output" {
    var dbg: std.heap.DebugAllocator(.{}) = .init;
    defer _ = dbg.deinit();
    const gpa = dbg.allocator();

    var run_arena: std.heap.ArenaAllocator = .init(gpa);
    defer run_arena.deinit();
    const run_alloc = run_arena.allocator();

    const code = try zag.marshal.pyc.loadBytes(run_alloc, hello_pyc);

    var out_buf: [4096]u8 = undefined;
    var writer = std.Io.Writer.fixed(&out_buf);
    var stderr_buf: [1024]u8 = undefined;
    var stderr_writer = std.Io.Writer.fixed(&stderr_buf);

    var interp = try zag.vm.interp.Interp.init(run_alloc, &writer, &stderr_writer);
    try interp.installBuiltins();
    _ = try interp.run(code);
    try writer.flush();

    try std.testing.expectEqualStrings(hello_stdout, writer.buffered());
}
