#!/usr/bin/env bash
# Regenerate .pyc + .expected.txt for every .py fixture in this directory,
# then emit fixtures.zig -- a tiny module the integration test iterates
# so new fixtures don't need a code change. Requires python3.14 on PATH.
#
# Top-level *.py become "fixture" entries (run + diff). Directories
# whose name starts with `_` are helper packages: every .py inside
# (recursively) is compiled and registered, but they don't run as
# fixtures themselves.
set -euo pipefail
cd "$(dirname "$0")"
PY=${PYTHON:-python3.14}

shopt -s nullglob
py_files=(*.py)
if [[ ${#py_files[@]} -eq 0 ]]; then
  echo "no .py fixtures found in $(pwd)" >&2
  exit 1
fi

for src in "${py_files[@]}"; do
  base=${src%.py}
  $PY -c "import py_compile; py_compile.compile('$src', cfile='${base}.cpython-314.pyc', doraise=True)"
  # In CI the committed expected.txt files are the ground truth; skip
  # regeneration so platform differences (e.g. macOS readline vs Linux
  # readline, macOS-only stat constants) don't clobber the committed
  # output.  Set REGEN=1 locally to force a full regeneration.
  if [[ -z "${CI:-}" || -n "${REGEN:-}" ]]; then
    if ! $PY "$src" > "${base}.expected.txt.tmp" 2>/dev/null; then
      rm -f "${base}.expected.txt.tmp"
    else
      mv "${base}.expected.txt.tmp" "${base}.expected.txt"
    fi
  fi
done

# Compile every .py inside helper-package directories (those whose
# basename starts with `_`). The .pyc lives next to the .py, mirroring
# the layout the loader expects.
pkg_pyc_paths=()
pkg_dirs=(_*/)
for dir in "${pkg_dirs[@]}"; do
  while IFS= read -r -d '' src; do
    base=${src%.py}
    pyc="${base}.cpython-314.pyc"
    $PY -c "import py_compile; py_compile.compile('$src', cfile='$pyc', doraise=True)"
    pkg_pyc_paths+=("$pyc")
  done < <(find "$dir" -name '*.py' -print0 | sort -z)
done

{
  echo "// Auto-generated by tests/fixtures/gen.sh. Do not edit."
  echo "pub const names = [_][]const u8{"
  for src in "${py_files[@]}"; do
    base=${src%.py}
    echo "    \"${base}\","
  done
  echo "};"
  echo ""
  echo "pub const Helper = struct {"
  echo "    /// Fully-qualified module name (e.g. \"_39pkg.sub.leaf\")."
  echo "    name: []const u8,"
  echo "    /// Path to the .pyc relative to tests/fixtures/."
  echo "    path: []const u8,"
  echo "    is_package: bool,"
  echo "};"
  echo ""
  echo "pub const helpers = [_]Helper{"
  for pyc in "${pkg_pyc_paths[@]}"; do
    rel=${pyc%.cpython-314.pyc}
    if [[ "${rel##*/}" == "__init__" ]]; then
      mod="${rel%/__init__}"
      mod="${mod//\//.}"
      echo "    .{ .name = \"${mod}\", .path = \"${pyc}\", .is_package = true },"
    else
      mod="${rel//\//.}"
      echo "    .{ .name = \"${mod}\", .path = \"${pyc}\", .is_package = false },"
    fi
  done
  echo "};"
} > fixtures.zig
