#!/usr/bin/env bash
# Regenerate .pyc + .expected.txt for every .py fixture in this directory,
# then emit fixtures.zig -- a tiny module the integration test iterates
# so new fixtures don't need a code change. Requires python3.14 on PATH.
set -euo pipefail
cd "$(dirname "$0")"
PY=${PYTHON:-python3.14}

shopt -s nullglob
py_files=(*.py)
if [[ ${#py_files[@]} -eq 0 ]]; then
  echo "no .py fixtures found in $(pwd)" >&2
  exit 1
fi

for src in "${py_files[@]}"; do
  base=${src%.py}
  $PY -c "import py_compile; py_compile.compile('$src', cfile='${base}.cpython-314.pyc', doraise=True)"
  $PY "$src" > "${base}.expected.txt"
done

{
  echo "// Auto-generated by tests/fixtures/gen.sh. Do not edit."
  echo "pub const names = [_][]const u8{"
  for src in "${py_files[@]}"; do
    base=${src%.py}
    echo "    \"${base}\","
  done
  echo "};"
} > fixtures.zig
